name: stere
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  # flutterfire_ui: ^0.4.3+17
  firebase_ui_auth: ^1.0.2
  firebase_ui_oauth: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  riverpod: ^2.0.2
  flutter_riverpod: ^2.0.2
  dynamic_color: ^1.5.4
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  shimmer: ^2.0.0
  image_picker: ^0.8.6
  dropdown_button2: ^1.8.9
  flutter_slidable: ^2.0.0
  badges: ^2.0.3
  duration: ^3.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated
